Fake News Detection


In [50]:
#Importing Required Library 

import pandas as pd  #for importing datasets and cleaning and analysis
import numpy as np  # used for scientific computations
import seaborn as sns #for plotting the graph 
import matplotlib.pyplot as plt # for plotting the graph
from sklearn.model_selection import train_test_split #Spliting the dataset onto taining and testing data in ratio 74.5:25.5
from sklearn.metrics import accuracy_score # finding the accuracy of the model
from sklearn.metrics import classification_report # finding the Precision, recall, f1-score and support 
import re # Regular expressation for text cleaning 
import string #text cleaning 

In [51]:
#Inserting fake and real dataset
df_fake=pd.read_csv("Data Set\Fake.csv");
df_true=pd.read_csv("Data Set\True.csv");


In [52]:
df_fake.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   
5  The number of cases of cops brutalizing and ki...    News   
6  Donald Trump spent a good portion of his day a...    News   
7  In the wake of yet another court decision that...    News   
8  Many people have raised the alarm regarding th...    News   
9  Just when you might have thought we d get a br...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017  
5  December 25, 2017  
6  December 23, 2017  
7  December 23, 2017  
8  December 22, 2017  
9  December 21, 2017

In [53]:
df_true.head(10)

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   
5  White House, Congress prepare for talks on spe...   
6  Trump says Russia probe will be fair, but time...   
7  Factbox: Trump on Twitter (Dec 29) - Approval ...   
8         Trump on Twitter (Dec 28) - Global Warming   
9  Alabama official to certify Senator-elect Jone...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   
5  WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...  politicsNews   
6  WEST PALM BEACH, Fla (Reuters) - President Don...  politicsNews   
7  The following statements were posted to the ve...  politicsNews   
8  The following statements were posted to the ve...  politicsNews   
9  WASHINGTON (Reuters) - Alabama Secretary of St...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017   
2  December 31, 2017   
3  December 30, 2017   
4  December 29, 2017   
5  December 29, 2017   
6  December 29, 2017   
7  December 29, 2017   
8  December 29, 2017   
9  December 28, 2017

In [54]:
#Inserting a column called 'class' for fake and real news dataset
#to categories fake and true news

#Inserting a column "class" as a target feature

df_fake["class"]=0
df_true["class"]=1

In [55]:
#Shape of the Fake and True News CSV
df_fake.shape, df_true.shape

((23481, 5), (21417, 5))

In [56]:
#Removing last 10 rows from both the data set, for manual testing
df_fake_manual_testing = df_fake.tail(10)
for i in range(23480,23470,-1):
      df_fake.drop([i], axis=0, inplace=True)
df_true_manual_testing = df_true.tail(10)
for i in range(21416,21406,-1):
      df_true.drop([i],axis=0,inplace=True)


In [57]:
#Now, after removing 10 rows from the dataset, Shape of the Fake and True News CSV
df_fake.shape, df_true.shape

((23471, 5), (21407, 5))

In [58]:
df_fake_manual_testing["class"]=0
df_true_manual_testing["class"]=1

C:\Users\dell\AppData\Local\Temp\ipykernel_12292\401406962.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fake_manual_testing["class"]=0
C:\Users\dell\AppData\Local\Temp\ipykernel_12292\401406962.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_true_manual_testing["class"]=1


In [59]:
df_fake_manual_testing.head(10)

title  \
23471  Seven Iranians freed in the prisoner swap have...   
23472                      #Hashtag Hell & The Fake Left   
23473  Astroturfing: Journalist Reveals Brainwashing ...   
23474          The New American Century: An Era of Fraud   
23475  Hillary Clinton: ‘Israel First’ (and no peace ...   
23476  McPain: John McCain Furious That Iran Treated ...   
23477  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...   
23478  Sunnistan: US and Allied ‘Safe Zone’ Plan to T...   
23479  How to Blow $700 Million: Al Jazeera America F...   
23480  10 U.S. Navy Sailors Held by Iranian Military ...   

                                                    text      subject  \
23471  21st Century Wire says This week, the historic...  Middle-east   
23472   By Dady Chery and Gilbert MercierAll writers ...  Middle-east   
23473  Vic Bishop Waking TimesOur reality is carefull...  Middle-east   
23474  Paul Craig RobertsIn the last years of the 20t...  Middle-east   
23475  Robert Fantina CounterpunchAlthough the United...  Middle-east   
23476  21st Century Wire says As 21WIRE reported earl...  Middle-east   
23477  21st Century Wire says It s a familiar theme. ...  Middle-east   
23478  Patrick Henningsen  21st Century WireRemember ...  Middle-east   
23479  21st Century Wire says Al Jazeera America will...  Middle-east   
23480  21st Century Wire says As 21WIRE predicted in ...  Middle-east   

                   date  class  
23471  January 20, 2016      0  
23472  January 19, 2016      0  
23473  January 19, 2016      0  
23474  January 19, 2016      0  
23475  January 18, 2016      0  
23476  January 16, 2016      0  
23477  January 16, 2016      0  
23478  January 15, 2016      0  
23479  January 14, 2016      0  
23480  January 12, 2016      0

In [60]:
df_true_manual_testing.head(10)

title  \
21407  Mata Pires, owner of embattled Brazil builder ...   
21408  U.S., North Korea clash at U.N. forum over nuc...   
21409  U.S., North Korea clash at U.N. arms forum on ...   
21410  Headless torso could belong to submarine journ...   
21411  North Korea shipments to Syria chemical arms a...   
21412  'Fully committed' NATO backs new U.S. approach...   
21413  LexisNexis withdrew two products from Chinese ...   
21414  Minsk cultural hub becomes haven from authorities   
21415  Vatican upbeat on possibility of Pope Francis ...   
21416  Indonesia to buy $1.14 billion worth of Russia...   

                                                    text    subject  \
21407  SAO PAULO (Reuters) - Cesar Mata Pires, the ow...  worldnews   
21408  GENEVA (Reuters) - North Korea and the United ...  worldnews   
21409  GENEVA (Reuters) - North Korea and the United ...  worldnews   
21410  COPENHAGEN (Reuters) - Danish police said on T...  worldnews   
21411  UNITED NATIONS (Reuters) - Two North Korean sh...  worldnews   
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...  worldnews   
21413  LONDON (Reuters) - LexisNexis, a provider of l...  worldnews   
21414  MINSK (Reuters) - In the shadow of disused Sov...  worldnews   
21415  MOSCOW (Reuters) - Vatican Secretary of State ...  worldnews   
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...  worldnews   

                   date  class  
21407  August 22, 2017       1  
21408  August 22, 2017       1  
21409  August 22, 2017       1  
21410  August 22, 2017       1  
21411  August 21, 2017       1  
21412  August 22, 2017       1  
21413  August 22, 2017       1  
21414  August 22, 2017       1  
21415  August 22, 2017       1  
21416  August 22, 2017       1

In [61]:
#Concatenating the two files which we split above.
df_manual_testing=pd.concat([df_fake_manual_testing,df_true_manual_testing],axis=0)
df_manual_testing.to_csv("manual_testing.csv")

In [62]:
#Merging True and Fake Dataframes

df_merge=pd.concat([df_fake,df_true],axis=0)
df_merge.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   
5  The number of cases of cops brutalizing and ki...    News   
6  Donald Trump spent a good portion of his day a...    News   
7  In the wake of yet another court decision that...    News   
8  Many people have raised the alarm regarding th...    News   
9  Just when you might have thought we d get a br...    News   

                date  class  
0  December 31, 2017      0  
1  December 31, 2017      0  
2  December 30, 2017      0  
3  December 29, 2017      0  
4  December 25, 2017      0  
5  December 25, 2017      0  
6  December 23, 2017      0  
7  December 23, 2017      0  
8  December 22, 2017      0  
9  December 21, 2017      0

In [63]:
df_merge.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='object')

Removing Columns which are not required

In [64]:
df=df_merge.drop(["title","subject","date"],axis=1)

In [65]:
#For the finding the null value of the datasets
df.isnull().sum()

text     0
class    0
dtype: int64

Random Shuffling the dataframe

In [66]:
#Because to remake the dataset random because when we merge the first fake columns comes then true To solving that problem we are shuffling the datasets.
df=df.sample(frac=1)

In [67]:
df.head()

text  class
15908  The FBI informant who went undercover to look ...      0
899    Rep. Adam Schiff (D-CA) is the Ranking Member ...      0
20258  ROME (Reuters) - Italy s lower house of parlia...      1
8728   The Bundy militia has now been making a nuisan...      0
17252  Remember Joni Ernst? Conservatives were so exc...      0

In [68]:
df.reset_index(inplace=True)
df.drop(["index"],axis=1,inplace=True)

In [69]:
df.columns

Index(['text', 'class'], dtype='object')

In [70]:
df.head()

text  class
0  The FBI informant who went undercover to look ...      0
1  Rep. Adam Schiff (D-CA) is the Ranking Member ...      0
2  ROME (Reuters) - Italy s lower house of parlia...      1
3  The Bundy militia has now been making a nuisan...      0
4  Remember Joni Ernst? Conservatives were so exc...      0

Creating a function to process the texts

In [71]:
#Cleaning the data
def wordopt(text):
    text = text.lower() # lowercase the data to format the dataset in a single format
    text = re.sub('\[.*?\]', '', text) #find the 1st argument in the 3rd argument and replace it by the 2nd one
    text = re.sub("\\W"," ",text) 
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)    
    return text

In [23]:
df["text"]=df["text"].apply(wordopt)  ## Recalling the function to clean the text.

Defining dependent and independent variables

In [24]:
x=df["text"] # dependent variable
y=df["class"] #independent variable
#predict the value of the class according to dependent variable

Splitting Training and Testing

In [25]:
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.255) 

Coverting text to vectors

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer  #To Covert the string to numerical data

vectorization=TfidfVectorizer()  
xv_train=vectorization.fit_transform(x_train) #vectorize
xv_test=vectorization.transform(x_test)#vectorize

Logistic Regression

In [27]:
from sklearn.linear_model import LogisticRegression

LR=LogisticRegression()
LR.fit(xv_train,y_train)

LogisticRegression()

In [28]:
pred_lr=LR.predict(xv_test)

In [29]:
LR.score(xv_test,y_test)


0.9875043691017127

In [30]:
print(classification_report(y_test,pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5964
           1       0.99      0.99      0.99      5480

    accuracy                           0.99     11444
   macro avg       0.99      0.99      0.99     11444
weighted avg       0.99      0.99      0.99     11444



In [31]:
#Confusion matrix for Logistic Regression
from sklearn.metrics import confusion_matrix
confusion_matrix(pred_lr,y_test)

array([[5889,   68],
       [  75, 5412]], dtype=int64)

Decision Tree Classification

In [32]:
from sklearn.tree import DecisionTreeClassifier


In [33]:
DT = DecisionTreeClassifier()
DT.fit(xv_train, y_train)

DecisionTreeClassifier()

In [34]:
pred_dt=DT.predict(xv_test)

In [35]:
DT.score(xv_test, y_test)

0.9956308982873121

In [36]:
print(classification_report(y_test, pred_dt))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5964
           1       1.00      0.99      1.00      5480

    accuracy                           1.00     11444
   macro avg       1.00      1.00      1.00     11444
weighted avg       1.00      1.00      1.00     11444



In [37]:
#Confusion matrix for Decision tree ckassificaton
confusion_matrix(pred_dt,y_test)

array([[5942,   28],
       [  22, 5452]], dtype=int64)

Gradient Boosting Classifier

In [38]:
from sklearn.ensemble import GradientBoostingClassifier

GBC = GradientBoostingClassifier(random_state=0)
GBC.fit(xv_train, y_train)

GradientBoostingClassifier(random_state=0)

In [39]:
pred_gbc=GBC.predict(xv_test)

In [40]:
GBC.score(xv_test,y_test)

0.9957182803215658

In [41]:
print(classification_report(y_test,pred_gbc))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      5964
           1       0.99      1.00      1.00      5480

    accuracy                           1.00     11444
   macro avg       1.00      1.00      1.00     11444
weighted avg       1.00      1.00      1.00     11444



In [42]:
#Confusion matrix for Gradient Boosting Classifier
confusion_matrix(pred_gbc,y_test)

array([[5930,   15],
       [  34, 5465]], dtype=int64)

Random Forest Classifier

In [43]:
from sklearn.ensemble import RandomForestClassifier

RFC=RandomForestClassifier(random_state=0)
RFC.fit(xv_train, y_train)


RandomForestClassifier(random_state=0)

In [44]:
pred_rfc=RFC.predict(xv_test)

In [45]:
RFC.score(xv_test, y_test)

0.9903005941978329

In [46]:
print(classification_report(y_test, pred_rfc))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5964
           1       0.99      0.99      0.99      5480

    accuracy                           0.99     11444
   macro avg       0.99      0.99      0.99     11444
weighted avg       0.99      0.99      0.99     11444



In [47]:
#Confusion matrix for Random forest Classifier
confusion_matrix(pred_rfc,y_test)

array([[5918,   65],
       [  46, 5415]], dtype=int64)

Manual Testing with Manual Entry news

In [48]:
def output_lable(n):
      if n==0:
            return "Fake News"
      elif n==1:
            return "Not a Fake News"

def manual_testing(news):
      testing_news={"text":[news]}
      new_def_test=pd.DataFrame(testing_news)
      new_def_test["text"]=new_def_test["text"].apply(wordopt)
      new_x_test=new_def_test["text"]
      new_xv_test=vectorization.transform(new_x_test)
      pred_LR=LR.predict(new_xv_test)
      pred_DT=DT.predict(new_xv_test)
      pred_GBC=GBC.predict(new_xv_test)
      pred_RFC=RFC.predict(new_xv_test)

      return print("\n\n LR Prediction: {} \n DT Prediction: {} \n GBC Prediction: {} \n RFC Prediction: {}".format(output_lable(pred_LR[0]),output_lable(pred_DT[0]),output_lable(pred_GBC[0]),output_lable(pred_RFC[0])))
      

In [74]:
news=str(input())
manual_testing(news)



 LR Prediction: Not a Fake News 
 DT Prediction: Fake News 
 GBC Prediction: Fake News 
 RFC Prediction: Not a Fake News


Noida officials on Friday said one nautical mile of air space around the twin Supertech towers will remain briefly unavailable for flights on August 28 during the demolition.


The civil aviation ministry has given its consent for the same, said officials overseeing preparations for demolition of the nearly 100m tall twin towers set to take place on Sunday.

"In view of the dust generated after the demolition, on the recommendation of the Noida Authority, the Ministry of Aviation has given its consent for the non-availability of one nautical mile of air space for aircraft to fly at the time of demolition," it said in a statement. A nautical mile is equal to approximately 1.8 km.

Arvind Kejriwal today called the BJP a "serial killer of governments" and said he wanted to face a trust vote just to prove that the party had failed to lure a single Aam Aadmi Party (AAP) MLA.
The AAP government will bring a confidence motion in the Delhi Assembly on Monday, sources say.

"I want to bring a confidence motion to show that the BJP has not been able to break away a single MLA," Arvind Kejriwal said, addressing a special session of the Delhi assembly.

AAP has called the session to discuss what it alleges is the BJP's "Operation Lotus" in Delhi to topple the Arvind Kejriwal government and the investigations targeting its leaders like Deputy Chief Minister Manish Sisodia, who has been charged over allegations of corruption in the Delhi liquor policy.